# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dropbox_token',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mendeley_token',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='url',
        ),
    ]
