# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 22:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('track_uuid', models.UUIDField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('dateCreated', models.DateTimeField()),
                ('speed', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('distance', models.FloatField()),
                ('dateCreated', models.DateTimeField()),
                ('dateClosed', models.DateTimeField()),
                ('comments', models.CharField(blank=True, default='', max_length=100)),
                ('type', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='point',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='locations.Track'),
        ),
    ]
