# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='accuracy',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='dateCreated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='lng',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='speed',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='track_uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='dateClosed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='dateCreated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='distance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='status',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='type',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='uuid',
            field=models.UUIDField(null=True),
        ),
    ]
