# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20151230_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='comments',
            field=models.TextField(null=True),
        ),
    ]
