# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20160108_2219'),
        ('locations', '0003_auto_20151231_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='authentication.Profile'),
        ),
    ]
