# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_track_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.Profile'),
        ),
    ]
