# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-06 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_auto_20160128_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ('dateCreated',)},
        ),
        migrations.AlterField(
            model_name='track',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
